# Generated by Django 4.1.2 on 2022-11-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'restaurant_type',
            },
        ),
        migrations.CreateModel(
            name='RestaurantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_style', models.CharField(max_length=30)),
                ('restaurant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.restauranttype')),
            ],
            options={
                'db_table': 'restaurant_style',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_street', models.CharField(max_length=30)),
                ('restaurant_type_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.restaurantstyle')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
